"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import sys

from setuptools import setup

sys.setrecursionlimit(5000)
APP = ["GCodeViewr_Vista.py"]
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
